Revert imports back to explicit
Reason: 
After compilation tslib errors out with the following message: 
```
TypeError: Class extends value undefined is not a constructor or null
```

After investigation the reason seems to be a circular dependency. To avoid further time investment reverted the imports structure back to very explicit. Might revisit in some future